# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ToDoList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'Realm' ,'10.38.0'
 pod 'RealmSwift' ,'10.38.0'

end
